---
layout: cv
title: Kenneth Halling's CV
---
# Kenneth Halling
Researcher, Writer, BYU-I Student.

<div id="webaddress">
<a href="https://github.com/kennyhalling">My GitHub</a>
</div>


## Currently

Majoring in Computer Science at BYU-Idaho and doing cybersecurity research on the side.

### Specialized in

Journalistic writing, leadership, C# language


### Research interests

Cybersecurity legislation, coding languages, database management


## Education

`2014 - 2025`
__McNeil High School, Austin, Texas.__

`April 2021 - Now`
__Brigham Young University - Idaho__

## Awards

`2018`
Eagle Scout, _"Boy Scouts of America"_, USA

## Occupation

`2023`
__Cybersecurity Researcher__, Crimson Vista, Remote Position

- Researched recent cybersecurity events
- Wrote weekly summaries about recent events

`2021-2023`
__Manufacturing Technician__, Sisu Devices, Austin, Texas

- Assembled high-quality machines to sharpen knives
- Collaborated with teammates to meet high quotas



<!-- ### Footer

Last updated: May 2013 -->